global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # API Bridge 서비스 메트릭 수집
  - job_name: 'api-bridge'
    static_configs:
      - targets: ['localhost:10019']
    metrics_path: '/metrics'
    scrape_interval: 5s
    scrape_timeout: 10s

  # Prometheus 자체 메트릭
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Grafana 메트릭 (선택사항)
  - job_name: 'grafana'
    static_configs:
      - targets: ['localhost:3000']
    scrape_interval: 30s

# 알림 규칙 파일 경로
rule_files:
  - "alerts.yml"

# Alertmanager 설정
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093
